name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v23.4.0
        uses: actions/setup-node@v4
        with:
            node-version: 23.4.0
            cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test
